### ISSUE TITLE
use git tags and release notes

### ISSUE THREAD

**Issue by sckott** [ropensci/essurvey#30]
we're trying to get all ropensci pkgs to use git tags and release notes, as it's common software practice.

In our packaging guide we have some notes on this https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news

We'd like each repo to have a git tag associated with each cran release and then the news items for that cran release on the releases tab of your repo. After you do the git tag, you'll then be able to go to Releases tab and edit the release notes for the git tag putting in your news items

thanks!

**Comment by cimentadaj** [comment]
Thanks @sckott ! I added the tag and NEWS release already has an entry for the latest version. What that what you meant?

**Comment by sckott** [comment]
there doesn't appear to be any git tags on your repo 

<img width="348" alt="screen shot 2018-06-09 at 8 38 25 am" src="https://user-images.githubusercontent.com/577668/41193436-8713dfa6-6bc0-11e8-88c4-3e3dbba85ca2.png">

I usually do it on the command line like `git tag v0.1.0 && git push origin v0.1.0` - but that's if im on the commit currently that gets the tag. You can also git tag a previous/older commit, check out https://git-scm.com/book/en/v2/Git-Basics-Tagging

No, i meant put your news items in releases like this https://github.com/ropensci/taxize/releases

**Comment by cimentadaj** [comment]
@sckott thanks for this, I wasn't aware either of tags or releases. Both should be implemented now.
