### ISSUE TITLE
import_country returns error

### ISSUE THREAD

**Issue by cknotz** [ropensci/essurvey#53]
Hi!

I was just trying to download ESS data using the `import_country()` function, but found that it returns an error. 

I ran:
`ess <- import_country(country = "Austria", rounds = 1)`

Result: Failed to download, and error message:
`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: www.europeansocialsurvey.orghttp`

I get the same error when I try to download data for Norway or Germany, and for round 9 instead of 1, or when I use the example from the help files (Denmark, rounds 1-3).

`import_rounds()` works as it should, however.

My environment:
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.1.2 (2021-11-01)
 os       macOS Big Sur 10.16         
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Oslo                 
 date     2021-12-13

Many thanks in advance!

**Comment by Jimbilben** [comment]
I have the same issue. Did you manage to resolve this @cknotz ?

**Comment by cknotz** [comment]
Nope, `import_country()` still does not work, and I haven't been able to dig through the different functions to figure out what exactly the issue is. 

_Edit:_ My hunch is that the problem is somewhere in the `url_funs.R` file. Judging from the error message, there is an issue with the construction of the URL to download the data from (notice: "www.europeansocialsurvey.**orghttp**"). No idea where this bug could be, though.

**Comment by Jimbilben** [comment]
Yes, it looks like the http is added on at the end and might mess things up? Strangely mine also works exactly like yours and will run import_rounds(). I've gotten around the issue by just using import rounds and then filtering out whatever countries I do/don't want - but it's a bit strange!

**Comment by cimentadaj** [comment]
Should be fixed now. Install again with `devtools::install_github("ropensci/essurvey")`. Let me know if you run into any errors.

**Comment by cimentadaj** [comment]
Submitted to CRAN, hopefully should be available soon.

**Comment by cknotz** [comment]
Dear Jorge, works like a charm! Many thanks! Could you perhaps make a quick post here once the new version is on CRAN? Cheers, Carlo

**Comment by cimentadaj** [comment]
On CRAN. Thanks for the report!

**Comment by cknotz** [comment]
Many, many thanks - helps a lot with teaching if packages are on CRAN!
