### ISSUE TITLE
SDDF pulling error

### ISSUE THREAD

**Issue by martroben** [ropensci/essurvey#55]
## Expected Behavior
Get SDDF

## Current Behavior & Steps to Reproduce
Getting an error when trying to download or get the sddf file
Seems that the host name gets corrupted somehow

> library("essurvey")
> essurvey::set_email("****.****@gmail.com")
> essurvey::download_sddf_country(country = "Estonia", rounds = 7)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: www.europeansocialsurvey.orghttp

## Context
Trying to get an SDDF file for round 7, which doesn't seem to be available on https://www.europeansocialsurvey.org/download.html?file=ESS8SDDFe01_1&y=2014 anymore

## Your Environment
> devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       macOS Big Sur 11.4
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Tallinn
 date     2022-01-09
 rstudio  2021.09.1+372 Ghost Orchid (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.1.0)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.1.0)
 cli           3.1.0   2021-10-27 [1] CRAN (R 4.1.0)
 colorspace    2.0-2   2021-06-24 [1] CRAN (R 4.1.0)
 crayon        1.4.2   2021-10-29 [1] CRAN (R 4.1.0)
 curl          4.3.2   2021-06-23 [1] CRAN (R 4.1.0)
 desc          1.4.0   2021-09-28 [1] CRAN (R 4.1.0)
 devtools      2.4.3   2021-11-30 [1] CRAN (R 4.1.0)
 dplyr         1.0.7   2021-06-18 [1] CRAN (R 4.1.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
 essurvey    * 1.0.7   2021-03-22 [1] CRAN (R 4.1.0)
 fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.0)
 generics      0.1.1   2021-10-25 [1] CRAN (R 4.1.0)
 ggplot2       3.3.5   2021-06-25 [1] CRAN (R 4.1.0)
 glue          1.6.0   2021-12-17 [1] CRAN (R 4.1.0)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 4.1.0)
 httr          1.4.2   2020-07-20 [1] CRAN (R 4.1.0)
 lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.0)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.1.0)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 4.1.0)
 pacman        0.5.1   2019-03-11 [1] CRAN (R 4.1.0)
 pillar        1.6.4   2021-10-18 [1] CRAN (R 4.1.0)
 pkgbuild      1.3.1   2021-12-20 [1] CRAN (R 4.1.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
 pkgload       1.2.4   2021-11-30 [1] CRAN (R 4.1.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.1.0)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.1.0)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.1.0)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.0)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.1.0)
 rlang         0.4.12  2021-10-18 [1] CRAN (R 4.1.0)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
 rvest         1.0.2   2021-10-16 [1] CRAN (R 4.1.0)
 scales        1.1.1   2020-05-11 [1] CRAN (R 4.1.0)
 selectr       0.4-2   2019-11-20 [1] CRAN (R 4.1.0)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.0)
 stringi       1.7.6   2021-11-29 [1] CRAN (R 4.1.0)
 stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
 testthat      3.1.1   2021-12-03 [1] CRAN (R 4.1.0)
 tibble        3.1.6   2021-11-07 [1] CRAN (R 4.1.0)
 tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.1.0)
 usethis       2.1.5   2021-12-09 [1] CRAN (R 4.1.0)
 utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
 withr         2.4.3   2021-11-30 [1] CRAN (R 4.1.0)
 xml2          1.3.3   2021-11-30 [1] CRAN (R 4.1.0)

 [1] /Library/Frameworks/R.framework/Versions/4.1/Resources/library

**Comment by cimentadaj** [comment]
Can you install the latest Github version with `devtools::install_github('ropensci/essurvey'` and try again?

**Comment by martroben** [comment]
Nope. Still status quo.


> remove.packages("essurvey")

Removing package from ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library’
(as ‘lib’ is unspecified)

> devtools::install_github('ropensci/essurvey')

Downloading GitHub repo ropensci/essurvey@HEAD
✓  checking for file ‘/private/var/folders/_x/9j3k84v13sj8r984ys34d6640000gn/T/Rtmp6YkxXL/remotes15aed48c2102c/ropensci-essurvey-b45b11a/DESCRIPTION’ (480ms)
─  preparing ‘essurvey’: (489ms)
✓  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘essurvey_1.0.8.tar.gz’
   
* installing *source* package ‘essurvey’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (essurvey)
 
> essurvey::set_email("xxx.xxx@gmail.com")
> essurvey::download_sddf_country(country = "Estonia", rounds = 7)

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: www.europeansocialsurvey.orghttp

**Comment by martroben** [comment]
Whoops, ignore last comment.
After restarting R, all good!
Thank you!

> essurvey::download_sddf_country(country = "Estonia", rounds = 7)

Downloading ESS7
  |===========================================================================================| 100%
All files saved to /Users/martroben/Projektid/R/Eurosurvey2014

**Comment by cimentadaj** [comment]
This version is on CRAN now, thanks for reporting!
